---
- name: Mark packages on hold.
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'exclude={{ item }}'
    state: present
  with_items: "{{ upgrade_packages_on_hold }}"

- name: Upgrade via DNF.
  dnf:
    name: "*"
    state: latest

- name: Cleanup via DNF.
  dnf:
    autoremove: yes
  ignore_errors: true # DNF Version too low

- name: Unhold packages.
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'exclude={{ item }}'
    state: absent
  with_items: "{{ upgrade_packages_on_hold }}"

- name: Install the latest version of dnf-utils
  dnf:
    name: dnf-utils
    state: latest

- name: Check for reboot hint.
  shell: dnf needs-restarting -r
  register: reboot_hint_dnf
  failed_when: reboot_hint_dnf.rc >= 2

- name: Set Reboot Hint.
  set_fact:
    reboot_hint: true
  when: reboot_hint_dnf.rc == 1
