---
- name: Preflight - Fail if target host is not stable for this Role.
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in upgrade_stable_os)

- name: Include package manager specific playbook.
  include_tasks: "{{ ansible_pkg_mgr }}.yml"

- name: Reboot Server.
  become: yes
  shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  when:
    - ((reboot_hint is defined and reboot_hint | bool) and (upgrade_unattended_reboot | bool)) or (upgrade_force_reboot | bool)

- name: Wait for server to restart.
  module: wait_for
    host={{ inventory_hostname }}
    port=22
    delay=10
    timeout=300
  become: false
  delegate_to: localhost
  when:
    - ((reboot_hint is defined and reboot_hint | bool) and (upgrade_unattended_reboot | bool)) or (upgrade_force_reboot | bool)
