---
- name: "Generate Report Files per Host."
  become: 'no'
  template:
    src: report.j2
    dest: "{{ upgrade_reporting_path }}/report_{{ inventory_hostname }}.txt"
  delegate_to: localhost

- name: "Empty Full Report File."
  become: 'no'
  shell: '/bin/printf "Generated: $(date)\n\n" > "{{ upgrade_reporting_path }}/report_full.txt"'
  delegate_to: localhost
  run_once: 'true'

- name: "Concatenate Report Files."
  become: 'no'
  shell: 'cat {{ upgrade_reporting_path }}/report_{{ inventory_hostname }}.txt >> {{ upgrade_reporting_path }}/report_full.txt'
  delegate_to: localhost
  throttle: 1

- name: "Send Reports per Mail."
  become: 'no'
  mail:
    host: "{{ upgrade_reporting_mail_host }}"
    port: "{{ upgrade_reporting_mail_port }}"
    username: "{{ upgrade_reporting_mail_user | default(omit) }}"
    password: "{{ upgrade_reporting_mail_password | default(omit) }}"
    subject: "{{ upgrade_reporting_mail_subject }}"
    body: "{{ lookup('file', '{{ upgrade_reporting_path }}/report_full.txt') }}"
    from: "{{ upgrade_reporting_mail_from }}"
    to: "{{ upgrade_reporting_mail_to }}"
    attach:
      - '{{ upgrade_reporting_path }}/report_full.txt'
  delegate_to: localhost
  run_once: "{{ upgrade_reporting_mail_run_once | bool }}"
  when: upgrade_reporting_mail_enable | bool

- name: "Send Reports via Telegram."
  become: 'no'
  community.general.telegram:
    token: "{{ upgrade_telegram_token }}"
    api_args:
      chat_id: "{{ upgrade_telegram_chatid }}"
      parse_mode: "MarkdownV2"
      text: "{{ lookup('file', '{{ upgrade_reporting_path }}/report_{{ inventory_hostname }}.txt') | replace('.','\\.') | replace(':','\\:') | replace('-','\\-') | replace('_','\\_') | replace('+','\\+') }}"
      disable_web_page_preview: True
      disable_notification: True
  delegate_to: localhost
  when: upgrade_reporting_telegram_enable | bool

- name: "Clean up Report Files."
  become: 'no'
  file:
    path: "{{ item }}"
    state: absent
  delegate_to: localhost
  loop:
    - "{{ upgrade_reporting_path }}/report_{{ inventory_hostname }}.txt"
    - "{{ upgrade_reporting_path }}/report_full.txt"
